import type { Metadata } from "next";
import '@/app/ui/globals.css';
import { inter, noto_sans } from '@/app/ui/fonts';
import Header from "./ui/header/header";

export const metadata: Metadata = {
  title: "ДЕШЁВАЯ ПЕЧАТЬ СТУДЕНТАМ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
